group:
  # Add each repo that should be synced here. One per line.
  - repos: |
      18f/methods
      18f/ux-guide
    files:
      - .github/workflows/sync_templates.yml
      - .github/sync.yml
      - source: .github/ISSUE_TEMPLATE/
        dest: .github/ISSUE_TEMPLATE/
        deleteOrphaned: true
      - source: .github/ISSUE_TEMPLATE.md
        dest: .github/ISSUE_TEMPLATE.md
        deleteOrphaned: true
      - source: .github/PULL_REQUEST_TEMPLATE/
        dest: .github/PULL_REQUEST_TEMPLATE/
        deleteOrphaned: true
      - source: .github/PULL_REQUEST_TEMPLATE.md
        dest: .github/PULL_REQUEST_TEMPLATE.md
        deleteOrphaned: true
