sudo: true
language: ruby
rvm:
- 2.1
script: bundle exec jekyll build --config _config.yml,_config-production.yml ./_site
deploy:
  provider: cloudfoundry
  edge: true
  api: https://api.cloud.gov
  organization: 18f
  space: methods
  username: deploy-18f
  password:
    secure: AnJqFN5TZS9QBhpO0ULqIZKJ7zsmuBqCv/D7HcWt/j0ZySBGyflcxYUZ8fkf0hejf9rCGv9WZDzg6KrJbVqMVONEBoC7ygSuc+SMFIEaa9WmNvs0JSWxo/apyleX0TSFbXiUJgd62TFavo2yyOKFGydKQfxs+w8VrsbgkiWzAnk=
  on:
    repo: 18F/methods
    branch: master
branches:
  only:
  - master
