sudo: true
language: ruby
rvm:
- 2.1
script: bundle exec jekyll build --config _config.yml,_config-production.yml ./_site
deploy:
  provider: cloudfoundry
  edge: true
  api: https://api.18f.gov
  organization: 18f
  space: methods
  username: deploy-18f
  password:
    secure: MaAE9DcvcS5Cg9+dme5PKYQ6Y7XFjdXgBcuGiQIeTATAIv3EeYuxLwjzdNrTyDDeQyKoEcBNQKNJr1XKMAFtCDA5KRp/9jtz/8hKGS9TFeMgJd9MbrWofnisg9mfoyJBz5W5sHCqcDNjBv0hi8pU3rcj2S/8B/n6jS4mMt7rxtI=
  on:
    repo: 18F/methods
    branch: master
branches:
  only:
    - master
