language: ruby
rvm:
- 2.1
script: bundle exec jekyll build --config _config.yml,_config-production.yml ./_site
deploy:
  provider: cloudfoundry
  edge: true
  api: https://api.cloud.gov
  organization: 18f
  space: methods
  username: 18f-methods_deployer
  password:
    secure: Oy3ypxrykXF3Kw5hrtYAfPgYnt3VLB2EcKCfMVpprfBDyNVu1LlbWgONSijdY2F55Ja1igaCEIE0lwncPYDflHXxghw7FeG2n7Bt3A3LR2u4SGBzecVLl6wvdz+mQuDEgZs7Ygft4nIJvt8ZzkvNKYah1hEEvbsVysmC33QfVpo=
  on:
    repo: 18F/methods
    branch: master
branches:
  only:
  - master
