markdown: redcarpet
name: Methods
exclude:
- CONTRIBUTING.md
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- go
- vendor

permalink: pretty
highlighter: rouge

sass:
  style: compressed

collections:
  pages:
    output: true
    permalink: /:path/
  methods:
    output: true
    permalink: /:path/
site:
  title: Methods

repos:
- name: Methods
  description: Main repository
  url: https://github.com/18F/methods

jekyll_get:
  - data: releases
    json: 'https://api.github.com/repos/18F/web-design-standards/releases'

google_analytics_ua: UA-48605964-19

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
