# Site settings
title: 18F Method Cards
email: andrew.maier@gsa.gov
baseurl: "/design-methods"
url: "http://method-cards.local" # the base hostname & protocol for your site
twitter_username: 18f
github_username:  18f
defaults:
  scope:
    path: "methods"
  values:
    layout: "method"

collections:
  methods:
    output: true
    permalink: /method/:name/
