markdown: redcarpet
name: Methods
exclude:
- CONTRIBUTING.md
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- go
- vendor

permalink: pretty
highlighter: rouge

collections:
  pages:
    output: true
    permalink: /:path/
  methods:
    output: true
site:
  title: Methods

repos:
- name: Methods
  description: Main repository
  url: https://github.com/18F/methods

google_analytics_ua: UA-48605964-19

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
