name: Label new issues

on:
  issues:
    types:
      - opened

jobs:
  initialize:
    name: Label new issue
    runs-on: ubuntu-latest
    steps:
      - name: add label
        uses: christianvuerings/add-labels@v1.1
        with:
          labels: new issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
